export interface Pregunta {
  texto: string
  opciones: string[]
  respuesta: number // índice 0-based de la opción correcta
}

export const PREGUNTAS: Pregunta[] = [
  { texto: '¿Quién escribió "Cien años de soledad"?', opciones: ['Pablo Neruda', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Julio Cortázar'], respuesta: 1 },
  { texto: '¿En qué país transcurre "Don Quijote de la Mancha"?', opciones: ['Portugal', 'Italia', 'España', 'Francia'], respuesta: 2 },
  { texto: '¿Quién escribió "Hamlet"?', opciones: ['Charles Dickens', 'William Shakespeare', 'Oscar Wilde', 'John Milton'], respuesta: 1 },
  { texto: '¿Cómo se llama el protagonista de "El Aleph"?', opciones: ['Borges', 'Fierro', 'Aureliano', 'Raskolnikov'], respuesta: 0 },
  { texto: '¿Quién escribió "La casa de los espíritus"?', opciones: ['Isabel Allende', 'Laura Esquivel', 'Elena Poniatowska', 'Rosario Castellanos'], respuesta: 0 },
  { texto: '¿En qué novela aparece el personaje Atticus Finch?', opciones: ['El gran Gatsby', 'Matar a un ruiseñor', 'Mientras agonizo', 'El sonido y la furia'], respuesta: 1 },
  { texto: '¿Quién escribió "Rayuela"?', opciones: ['Ernesto Sábato', 'Julio Cortázar', 'Jorge Luis Borges', 'Adolfo Bioy Casares'], respuesta: 1 },
  { texto: '¿Cuál es el apellido del protagonista de "Crimen y castigo"?', opciones: ['Karenin', 'Karamazov', 'Raskolnikov', 'Oblomov'], respuesta: 2 },
  { texto: '¿Quién escribió "Orgullo y prejuicio"?', opciones: ['Charlotte Brontë', 'Mary Shelley', 'George Eliot', 'Jane Austen'], respuesta: 3 },
  { texto: '¿En qué siglo vivió Miguel de Cervantes?', opciones: ['XIV', 'XV', 'XVI-XVII', 'XVIII'], respuesta: 2 },
  { texto: '¿Quién es el autor de "El extranjero"?', opciones: ['Jean-Paul Sartre', 'Albert Camus', 'Simone de Beauvoir', 'André Gide'], respuesta: 1 },
  { texto: '¿Cómo se llama la ballena blanca en "Moby Dick"?', opciones: ['Moby', 'Leviatán', 'No tiene nombre propio', 'Moby Dick'], respuesta: 3 },
  { texto: '¿Quién escribió "1984"?', opciones: ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H.G. Wells'], respuesta: 2 },
  { texto: '¿Qué narrador usa "El gran Gatsby"?', opciones: ['Jay Gatsby', 'Daisy Buchanan', 'Nick Carraway', 'Tom Buchanan'], respuesta: 2 },
  { texto: '¿Quién escribió "Ficciones"?', opciones: ['Julio Cortázar', 'Jorge Luis Borges', 'Bioy Casares', 'Roberto Arlt'], respuesta: 1 },
  { texto: '¿En qué obra de Shakespeare aparece Ofelia?', opciones: ['Macbeth', 'Otelo', 'El rey Lear', 'Hamlet'], respuesta: 3 },
  { texto: '¿Quién escribió "Pedro Páramo"?', opciones: ['Carlos Fuentes', 'Juan Rulfo', 'Augusto Monterroso', 'José Emilio Pacheco'], respuesta: 1 },
  { texto: '¿Cuál es la primera línea de "Anna Karénina"?', opciones: ['Todo era oscuridad y silencio', 'Todas las familias felices se parecen', 'Llámame Ismael', 'Era el mejor de los tiempos'], respuesta: 1 },
  { texto: '¿Quién escribió "El señor de los anillos"?', opciones: ['C.S. Lewis', 'J.R.R. Tolkien', 'Terry Pratchett', 'George R.R. Martin'], respuesta: 1 },
  { texto: '¿Qué personaje vive en Baker Street 221B?', opciones: ['Hercule Poirot', 'Philip Marlowe', 'Sherlock Holmes', 'Auguste Dupin'], respuesta: 2 },
  { texto: '¿Quién escribió "La metamorfosis"?', opciones: ['Stefan Zweig', 'Thomas Mann', 'Hermann Hesse', 'Franz Kafka'], respuesta: 3 },
  { texto: '¿En qué ciudad transcurre "Ulises" de James Joyce?', opciones: ['Londres', 'Dublín', 'Edimburgo', 'Belfast'], respuesta: 1 },
  { texto: '¿Quién escribió "Los miserables"?', opciones: ['Gustave Flaubert', 'Honoré de Balzac', 'Émile Zola', 'Victor Hugo'], respuesta: 3 },
  { texto: '¿Cómo se llama el protagonista de "El proceso" de Kafka?', opciones: ['Gregor Samsa', 'Josef K.', 'Karl Rossmann', 'Georg Bendemann'], respuesta: 1 },
  { texto: '¿Qué autor ganó el Nobel con "Beloved"?', opciones: ['Maya Angelou', 'Alice Walker', 'Toni Morrison', 'Zora Neale Hurston'], respuesta: 2 },
  { texto: '¿Quién escribió "Don Segundo Sombra"?', opciones: ['José Hernández', 'Ricardo Güiraldes', 'Leopoldo Lugones', 'Horacio Quiroga'], respuesta: 1 },
  { texto: '¿En qué obra aparece el personaje Huckleberry Finn?', opciones: ['Tom Sawyer', 'Las aventuras de Huck Finn', 'Ambos', 'Ninguno'], respuesta: 2 },
  { texto: '¿Quién escribió "Frankenstein"?', opciones: ['Bram Stoker', 'Ann Radcliffe', 'Mary Shelley', 'Edgar Allan Poe'], respuesta: 2 },
  { texto: '¿De qué país era el autor de "El túnel"?', opciones: ['Chile', 'Uruguay', 'Argentina', 'México'], respuesta: 2 },
  { texto: '¿Quién escribió "Middlemarch"?', opciones: ['Jane Austen', 'George Eliot', 'Elizabeth Gaskell', 'Thomas Hardy'], respuesta: 1 },
  { texto: '¿En qué década se publicó "Cien años de soledad"?', opciones: ['1950', '1960', '1970', '1980'], respuesta: 1 },
  { texto: '¿Qué movimiento literario lideró García Márquez junto a otros autores latinoamericanos?', opciones: ['Romanticismo', 'Modernismo', 'Realismo mágico', 'Surrealismo'], respuesta: 2 },
  { texto: '¿Quién escribió "El amor en los tiempos del cólera"?', opciones: ['Mario Vargas Llosa', 'Gabriel García Márquez', 'Jorge Amado', 'Isabel Allende'], respuesta: 1 },
  { texto: '¿Cuál es el nombre del protagonista de "El principito"?', opciones: ['El Principito', 'Petit', 'No tiene nombre', 'Pepito'], respuesta: 0 },
  { texto: '¿Quién escribió "El principito"?', opciones: ['Jules Verne', 'Antoine de Saint-Exupéry', 'Albert Camus', 'Jean Cocteau'], respuesta: 1 },
  { texto: '¿En qué obra aparece el personaje Jean Valjean?', opciones: ['El conde de Montecristo', 'Los miserables', 'Germinal', 'Nana'], respuesta: 1 },
  { texto: '¿Quién escribió "Los detectives salvajes"?', opciones: ['Roberto Bolaño', 'César Aira', 'Ricardo Piglia', 'Juan Villoro'], respuesta: 0 },
  { texto: '¿Qué novela comienza con "Llámame Ismael"?', opciones: ['Billy Budd', 'Lord Jim', 'Moby Dick', 'Nostromo'], respuesta: 2 },
  { texto: '¿Quién escribió "Madame Bovary"?', opciones: ['Victor Hugo', 'Honoré de Balzac', 'Gustave Flaubert', 'Stendhal'], respuesta: 2 },
  { texto: '¿Quién escribió "Crimen y castigo"?', opciones: ['León Tolstói', 'Fiódor Dostoyevski', 'Iván Turguénev', 'Nikolái Gógol'], respuesta: 1 },
  { texto: '¿Qué novela de Kafka termina sin final explícito porque murió antes de terminarla?', opciones: ['La metamorfosis', 'El proceso', 'El castillo', 'América'], respuesta: 2 },
  { texto: '¿Quién escribió "Cumbres borrascosas"?', opciones: ['Jane Austen', 'Charlotte Brontë', 'Emily Brontë', 'Anne Brontë'], respuesta: 2 },
  { texto: '¿Qué autor argentino escribió "Sobre héroes y tumbas"?', opciones: ['Jorge Luis Borges', 'Ernesto Sábato', 'Julio Cortázar', 'Manuel Puig'], respuesta: 1 },
  { texto: '¿Quién escribió "El nombre de la rosa"?', opciones: ['Umberto Eco', 'Italo Calvino', 'Leonardo Sciascia', 'Luigi Pirandello'], respuesta: 0 },
  { texto: '¿En qué idioma escribió originalmente "La divina comedia"?', opciones: ['Latín', 'Italiano antiguo (toscano)', 'Francés', 'Provenzal'], respuesta: 1 },
  { texto: '¿Quién escribió "La divina comedia"?', opciones: ['Petrarca', 'Boccaccio', 'Dante Alighieri', 'Ariosto'], respuesta: 2 },
  { texto: '¿Cuál es el apellido de los protagonistas de "Orgullo y prejuicio"?', opciones: ['Bennet', 'Darcy', 'Woodhouse', 'Dashwood'], respuesta: 0 },
  { texto: '¿Quién escribió "El retrato de Dorian Gray"?', opciones: ['Arthur Conan Doyle', 'Oscar Wilde', 'Robert Louis Stevenson', 'Bram Stoker'], respuesta: 1 },
  { texto: '¿Cuántos libros tiene la saga "Harry Potter"?', opciones: ['5', '6', '7', '8'], respuesta: 2 },
  { texto: '¿Quién es el autor de "El hobbit"?', opciones: ['C.S. Lewis', 'J.R.R. Tolkien', 'Philip Pullman', 'Ursula K. Le Guin'], respuesta: 1 },
  { texto: '¿Qué Premio Nobel de Literatura ganó Pablo Neruda?', opciones: ['1961', '1967', '1971', '1975'], respuesta: 2 },
  { texto: '¿Quién escribió "Bodas de sangre"?', opciones: ['Antonio Machado', 'Federico García Lorca', 'Rafael Alberti', 'Miguel Hernández'], respuesta: 1 },
  { texto: '¿En qué siglo vivió William Shakespeare?', opciones: ['XIV-XV', 'XV-XVI', 'XVI-XVII', 'XVII-XVIII'], respuesta: 2 },
  { texto: '¿Quién escribió "La náusea"?', opciones: ['Albert Camus', 'Jean-Paul Sartre', 'Simone de Beauvoir', 'Maurice Merleau-Ponty'], respuesta: 1 },
  { texto: '¿Cómo se llama el mayordomo de "El gran Gatsby"?', opciones: ['No tiene', 'James', 'Thomas', 'Wilson'], respuesta: 0 },
  { texto: '¿Quién escribió "El jugador" y "Los hermanos Karamázov"?', opciones: ['León Tolstói', 'Iván Turguénev', 'Fiódor Dostoyevski', 'Antón Chéjov'], respuesta: 2 },
  { texto: '¿Qué autor colombiano ganó el Nobel de Literatura en 1982?', opciones: ['Jorge Isaacs', 'Rafael Pombo', 'Gabriel García Márquez', 'Tomás González'], respuesta: 2 },
  { texto: '¿Quién escribió "2001: Odisea del espacio"?', opciones: ['Isaac Asimov', 'Arthur C. Clarke', 'Ray Bradbury', 'Philip K. Dick'], respuesta: 1 },
  { texto: '¿En qué país nació Gabriel García Márquez?', opciones: ['Venezuela', 'Colombia', 'México', 'Perú'], respuesta: 1 },
  { texto: '¿Qué movimiento literario representa Edgar Allan Poe?', opciones: ['Romanticismo oscuro / gótico', 'Realismo', 'Naturalismo', 'Modernismo'], respuesta: 0 },
  { texto: '¿Quién escribió "La guerra y la paz"?', opciones: ['Fiódor Dostoyevski', 'Antón Chéjov', 'León Tolstói', 'Iván Turguénev'], respuesta: 2 },
  { texto: '¿Cuántos años tiene el protagonista al inicio de "El guardián entre el centeno"?', opciones: ['14', '15', '16', '17'], respuesta: 2 },
  { texto: '¿Quién escribió "El guardián entre el centeno"?', opciones: ['J.D. Salinger', 'Jack Kerouac', 'F. Scott Fitzgerald', 'Ernest Hemingway'], respuesta: 0 },
  { texto: '¿Cuál es el subtítulo de "Frankenstein"?', opciones: ['El monstruo moderno', 'El Prometeo moderno', 'El experimento', 'El creador'], respuesta: 1 },
  { texto: '¿Quién escribió "Crónica de una muerte anunciada"?', opciones: ['Isabel Allende', 'Mario Vargas Llosa', 'Gabriel García Márquez', 'Carlos Fuentes'], respuesta: 2 },
  { texto: '¿En qué país transcurre "Doña Bárbara" de Rómulo Gallegos?', opciones: ['Colombia', 'Ecuador', 'Venezuela', 'Bolivia'], respuesta: 2 },
  { texto: '¿Quién escribió "El Martín Fierro"?', opciones: ['Ricardo Güiraldes', 'Esteban Echeverría', 'José Hernández', 'Domingo Sarmiento'], respuesta: 2 },
  { texto: '¿Qué forma poética usa "El Martín Fierro"?', opciones: ['Soneto', 'Haiku', 'Décimas (sextinas gauchescas)', 'Verso libre'], respuesta: 2 },
  { texto: '¿Quién escribió "Fahrenheit 451"?', opciones: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'Philip K. Dick'], respuesta: 2 },
  { texto: '¿Qué significa el número 451 en "Fahrenheit 451"?', opciones: ['El año en que ocurre', 'La temperatura a la que arde el papel', 'El número de página clave', 'El código secreto de los rebeldes'], respuesta: 1 },
  { texto: '¿Quién escribió "Lolita"?', opciones: ['Philip Roth', 'John Updike', 'Vladimir Nabokov', 'Saul Bellow'], respuesta: 2 },
  { texto: '¿En qué idioma escribió originalmente Nabokov "Lolita"?', opciones: ['Ruso', 'Francés', 'Inglés', 'Alemán'], respuesta: 2 },
  { texto: '¿Quién escribió "El alquimista"?', opciones: ['Jorge Amado', 'Paulo Coelho', 'Clarice Lispector', 'Machado de Assis'], respuesta: 1 },
  { texto: '¿Quién escribió "Fiesta" (The Sun Also Rises)?', opciones: ['F. Scott Fitzgerald', 'Ernest Hemingway', 'John Steinbeck', 'William Faulkner'], respuesta: 1 },
  { texto: '¿Cómo se llama el robot que aparece en "Yo, Robot" de Asimov?', opciones: ['Hal 9000', 'R2D2', 'Robbie', 'Data'], respuesta: 2 },
  { texto: '¿Quién escribió "La insoportable levedad del ser"?', opciones: ['Milan Kundera', 'Bohumil Hrabal', 'Václav Havel', 'Josef Škvorecký'], respuesta: 0 },
  { texto: '¿En qué ciudad transcurre "El perfume" de Patrick Süskind?', opciones: ['Berlín', 'Viena', 'París', 'Londres'], respuesta: 2 },
  { texto: '¿Quién escribió "Como agua para chocolate"?', opciones: ['Ángeles Mastretta', 'Laura Esquivel', 'Elena Poniatowska', 'Rosario Castellanos'], respuesta: 1 },
  { texto: '¿Qué país de origen tiene el autor de "El otoño del patriarca"?', opciones: ['Venezuela', 'Colombia', 'Cuba', 'México'], respuesta: 1 },
  { texto: '¿Quién escribió "Los pasos perdidos"?', opciones: ['Jorge Amado', 'Alejo Carpentier', 'Guillermo Cabrera Infante', 'José Lezama Lima'], respuesta: 1 },
  { texto: '¿Quién escribió "Ficciones"?', opciones: ['Julio Cortázar', 'Jorge Luis Borges', 'Macedonio Fernández', 'Silvina Ocampo'], respuesta: 1 },
  { texto: '¿Qué significa "haiku"?', opciones: ['Poema de veinte sílabas', 'Poema corto japonés de tres versos', 'Canción popular china', 'Relato breve coreano'], respuesta: 1 },
  { texto: '¿Quién escribió los poemas de "Residencia en la tierra"?', opciones: ['César Vallejo', 'Pablo Neruda', 'Octavio Paz', 'Vicente Huidobro'], respuesta: 1 },
  { texto: '¿En qué ciudad nació Pablo Neruda?', opciones: ['Santiago', 'Parral', 'Valparaíso', 'Temuco'], respuesta: 1 },
  { texto: '¿Qué escritor inventó al detective Auguste Dupin?', opciones: ['Arthur Conan Doyle', 'Agatha Christie', 'Edgar Allan Poe', 'Wilkie Collins'], respuesta: 2 },
  { texto: '¿Quién escribió "La condición humana"?', opciones: ['André Malraux', 'Albert Camus', 'Jean-Paul Sartre', 'André Gide'], respuesta: 0 },
  { texto: '¿En qué obra de García Márquez salen los Buendía?', opciones: ['El otoño del patriarca', 'El amor en los tiempos del cólera', 'Cien años de soledad', 'La hojarasca'], respuesta: 2 },
  { texto: '¿Cuántas obras de teatro escribió Shakespeare aproximadamente?', opciones: ['20', '27', '37', '45'], respuesta: 2 },
  { texto: '¿Quién escribió "Las flores del mal"?', opciones: ['Paul Verlaine', 'Arthur Rimbaud', 'Stéphane Mallarmé', 'Charles Baudelaire'], respuesta: 3 },
  { texto: '¿Quién escribió "El túnel"?', opciones: ['Jorge Luis Borges', 'Julio Cortázar', 'Ernesto Sábato', 'Adolfo Bioy Casares'], respuesta: 2 },
  { texto: '¿Quién escribió "Pantaleón y las visitadoras"?', opciones: ['Jorge Luis Borges', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Julio Cortázar'], respuesta: 2 },
  { texto: '¿Quién es el autor de "Rayuela"?', opciones: ['Ernesto Sábato', 'Julio Cortázar', 'Manuel Puig', 'Roberto Arlt'], respuesta: 1 },
  { texto: '¿En qué ciudad vive el detective Hercule Poirot de Agatha Christie?', opciones: ['París', 'Bruselas', 'Londres', 'Ginebra'], respuesta: 2 },
  { texto: '¿Quién escribió "El conde de Montecristo"?', opciones: ['Victor Hugo', 'Alexandre Dumas', 'Émile Zola', 'Stendhal'], respuesta: 1 },
  { texto: '¿Cuál es el nombre real de Mark Twain?', opciones: ['Thomas Clemens', 'Samuel Clemens', 'James Twain', 'Michael Twain'], respuesta: 1 },
  { texto: '¿Quién escribió "La vorágine"?', opciones: ['Rómulo Gallegos', 'José Eustasio Rivera', 'Jorge Isaacs', 'Eduardo Caballero Calderón'], respuesta: 1 },
  { texto: '¿Qué escritor chileno ganó el Nobel de Literatura en 1945?', opciones: ['Pablo Neruda', 'Vicente Huidobro', 'Gabriela Mistral', 'Nicanor Parra'], respuesta: 2 },
  { texto: '¿Quién escribió "Conversación en la catedral"?', opciones: ['Julio Cortázar', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Carlos Fuentes'], respuesta: 2 },
  { texto: '¿En qué formato está escrita "Rayuela" de Cortázar?', opciones: ['Novela lineal', 'Novela que puede leerse en múltiples órdenes', 'Cuentos intercalados', 'Diario íntimo'], respuesta: 1 },
  { texto: '¿Quién escribió "Veinte poemas de amor y una canción desesperada"?', opciones: ['César Vallejo', 'García Lorca', 'Pablo Neruda', 'Rubén Darío'], respuesta: 2 },
  { texto: '¿Quién escribió "Los olvidados" (libro, no película)?', opciones: ['Juan Rulfo', 'No existe como libro', 'Carlos Monsiváis', 'José Revueltas'], respuesta: 1 },
  { texto: '¿Quién escribió "El jugador" de Dostoyevski?', opciones: ['Fiódor Dostoyevski', 'León Tolstói', 'Antón Chéjov', 'Aleksandr Pushkin'], respuesta: 0 },
  { texto: '¿Cuántos libros componen "El señor de los anillos" como novela?', opciones: ['1', '2', '3', '6'], respuesta: 0 },
  { texto: '¿Quién escribió "La muerte de Artemio Cruz"?', opciones: ['Juan Rulfo', 'Carlos Fuentes', 'Octavio Paz', 'Agustín Yáñez'], respuesta: 1 },

  // ── Bloque 2 ─────────────────────────────────────────────────────────────
  { texto: '¿Quién escribió "Canto general"?', opciones: ['César Vallejo', 'Pablo Neruda', 'Octavio Paz', 'Vicente Huidobro'], respuesta: 1 },
  { texto: '¿Quién escribió "Los heraldos negros"?', opciones: ['César Vallejo', 'Pablo Neruda', 'Jorge Luis Borges', 'Rubén Darío'], respuesta: 0 },
  { texto: '¿Quién escribió "Trilce"?', opciones: ['Pablo Neruda', 'César Vallejo', 'Octavio Paz', 'Nicanor Parra'], respuesta: 1 },
  { texto: '¿En qué país nació César Vallejo?', opciones: ['Chile', 'Ecuador', 'Perú', 'Bolivia'], respuesta: 2 },
  { texto: '¿Quién escribió "El laberinto de la soledad"?', opciones: ['Carlos Fuentes', 'Octavio Paz', 'Juan Rulfo', 'Alfonso Reyes'], respuesta: 1 },
  { texto: '¿Quién escribió "Aura"?', opciones: ['Gabriel García Márquez', 'Carlos Fuentes', 'Julio Cortázar', 'José Donoso'], respuesta: 1 },
  { texto: '¿Quién escribió "El obsceno pájaro de la noche"?', opciones: ['Jorge Donoso', 'Mario Vargas Llosa', 'José Donoso', 'Guillermo Cabrera Infante'], respuesta: 2 },
  { texto: '¿Quién escribió "Tres tristes tigres"?', opciones: ['José Lezama Lima', 'Alejo Carpentier', 'Guillermo Cabrera Infante', 'Severo Sarduy'], respuesta: 2 },
  { texto: '¿Quién escribió "El recurso del método"?', opciones: ['Alejo Carpentier', 'José Lezama Lima', 'Guillermo Cabrera Infante', 'Severo Sarduy'], respuesta: 0 },
  { texto: '¿Quién escribió "El siglo de las luces"?', opciones: ['José Lezama Lima', 'Alejo Carpentier', 'Miguel Ángel Asturias', 'Augusto Roa Bastos'], respuesta: 1 },
  { texto: '¿Quién escribió "El señor presidente"?', opciones: ['Rómulo Gallegos', 'Miguel Ángel Asturias', 'Alejo Carpentier', 'Augusto Roa Bastos'], respuesta: 1 },
  { texto: '¿Quién escribió "Yo, el supremo"?', opciones: ['Augusto Roa Bastos', 'Miguel Ángel Asturias', 'Juan Carlos Onetti', 'Mario Benedetti'], respuesta: 0 },
  { texto: '¿De qué país era Juan Carlos Onetti?', opciones: ['Argentina', 'Chile', 'Uruguay', 'Paraguay'], respuesta: 2 },
  { texto: '¿Quién escribió "El astillero"?', opciones: ['Mario Benedetti', 'Juan Carlos Onetti', 'Felisberto Hernández', 'Carlos Martínez Moreno'], respuesta: 1 },
  { texto: '¿Quién escribió "La tregua"?', opciones: ['Juan Carlos Onetti', 'Mario Benedetti', 'Eduardo Galeano', 'Idea Vilariño'], respuesta: 1 },
  { texto: '¿Quién escribió "Las venas abiertas de América Latina"?', opciones: ['Mario Benedetti', 'Eduardo Galeano', 'Ernesto Che Guevara', 'Jorge Castañeda'], respuesta: 1 },
  { texto: '¿Quién escribió "Zama"?', opciones: ['Leopoldo Marechal', 'Antonio Di Benedetto', 'Haroldo Conti', 'Ricardo Piglia'], respuesta: 1 },
  { texto: '¿Quién escribió "Adán Buenosayres"?', opciones: ['Roberto Arlt', 'Leopoldo Marechal', 'Eduardo Mallea', 'Ernesto Sábato'], respuesta: 1 },
  { texto: '¿Quién escribió "Los siete locos"?', opciones: ['Leopoldo Marechal', 'Roberto Arlt', 'Adolfo Bioy Casares', 'Manuel Gálvez'], respuesta: 1 },
  { texto: '¿Quién escribió "La invención de Morel"?', opciones: ['Jorge Luis Borges', 'Julio Cortázar', 'Adolfo Bioy Casares', 'Silvina Ocampo'], respuesta: 2 },
  { texto: '¿Quién escribió "El jardín de los senderos que se bifurcan"?', opciones: ['Julio Cortázar', 'Jorge Luis Borges', 'Adolfo Bioy Casares', 'Silvina Ocampo'], respuesta: 1 },
  { texto: '¿En qué colección de cuentos de Borges aparece "La biblioteca de Babel"?', opciones: ['El Aleph', 'Ficciones', 'Historia universal de la infamia', 'El libro de arena'], respuesta: 1 },
  { texto: '¿Quién escribió "Bestiario"?', opciones: ['Jorge Luis Borges', 'Julio Cortázar', 'Adolfo Bioy Casares', 'Silvina Ocampo'], respuesta: 1 },
  { texto: '¿Quién escribió "Historia de cronopios y de famas"?', opciones: ['Julio Cortázar', 'Jorge Luis Borges', 'Marco Denevi', 'Marco Denevi'], respuesta: 0 },
  { texto: '¿Quién escribió "Boquitas pintadas"?', opciones: ['Manuel Puig', 'Osvaldo Soriano', 'Haroldo Conti', 'Ricardo Piglia'], respuesta: 0 },
  { texto: '¿Quién escribió "El beso de la mujer araña"?', opciones: ['Osvaldo Soriano', 'Manuel Puig', 'Ricardo Piglia', 'Juan Martini'], respuesta: 1 },
  { texto: '¿Quién escribió "Respiración artificial"?', opciones: ['Manuel Puig', 'Osvaldo Soriano', 'Ricardo Piglia', 'César Aira'], respuesta: 2 },
  { texto: '¿Quién escribió "No habrá más penas ni olvido"?', opciones: ['Ricardo Piglia', 'Osvaldo Soriano', 'Manuel Puig', 'Rodolfo Walsh'], respuesta: 1 },
  { texto: '¿Quién escribió "Operación Masacre"?', opciones: ['Osvaldo Soriano', 'Rodolfo Walsh', 'David Viñas', 'León Rozitchner'], respuesta: 1 },
  { texto: '¿Quién escribió "Santa Evita"?', opciones: ['Osvaldo Soriano', 'Tomás Eloy Martínez', 'Abel Posse', 'Andrés Rivera'], respuesta: 1 },
  { texto: '¿Quién escribió "La traición de Rita Hayworth"?', opciones: ['Osvaldo Soriano', 'Manuel Puig', 'César Aira', 'Alan Pauls'], respuesta: 1 },
  { texto: '¿Quién escribió "El entenado"?', opciones: ['César Aira', 'Juan José Saer', 'Ricardo Piglia', 'Tomás Eloy Martínez'], respuesta: 1 },
  { texto: '¿Quién escribió "2666"?', opciones: ['Roberto Bolaño', 'Javier Marías', 'Carlos Ruiz Zafón', 'Enrique Vila-Matas'], respuesta: 0 },
  { texto: '¿De qué país era Roberto Bolaño?', opciones: ['Argentina', 'México', 'Chile', 'España'], respuesta: 2 },
  { texto: '¿Quién escribió "La sombra del viento"?', opciones: ['Arturo Pérez-Reverte', 'Carlos Ruiz Zafón', 'Javier Marías', 'Eduardo Mendoza'], respuesta: 1 },
  { texto: '¿Quién escribió "El capitán Alatriste"?', opciones: ['Carlos Ruiz Zafón', 'Arturo Pérez-Reverte', 'Javier Marías', 'Antonio Muñoz Molina'], respuesta: 1 },
  { texto: '¿Quién escribió "Corazón tan blanco"?', opciones: ['Arturo Pérez-Reverte', 'Antonio Muñoz Molina', 'Javier Marías', 'Eduardo Mendoza'], respuesta: 2 },
  { texto: '¿Quién escribió "El jinete polaco"?', opciones: ['Javier Marías', 'Antonio Muñoz Molina', 'Eduardo Mendoza', 'Juan Goytisolo'], respuesta: 1 },
  { texto: '¿Quién escribió "Tiempo de silencio"?', opciones: ['Juan Goytisolo', 'Luis Martín-Santos', 'Camilo José Cela', 'Miguel Delibes'], respuesta: 1 },
  { texto: '¿Quién escribió "La familia de Pascual Duarte"?', opciones: ['Miguel Delibes', 'Camilo José Cela', 'Gonzalo Torrente Ballester', 'Juan Benet'], respuesta: 1 },
  { texto: '¿Quién escribió "La colmena"?', opciones: ['Miguel Delibes', 'Camilo José Cela', 'Juan Goytisolo', 'Carmen Laforet'], respuesta: 1 },
  { texto: '¿Quién escribió "Nada"?', opciones: ['Carmen Laforet', 'Ana María Matute', 'Mercè Rodoreda', 'Josefina Aldecoa'], respuesta: 0 },
  { texto: '¿Quién escribió "La plaça del Diamant"?', opciones: ['Mercè Rodoreda', 'Carmen Laforet', 'Ana María Matute', 'Montserrat Roig'], respuesta: 0 },
  { texto: '¿Quién escribió "El nombre de la rosa"?', opciones: ['Italo Calvino', 'Umberto Eco', 'Leonardo Sciascia', 'Pier Paolo Pasolini'], respuesta: 1 },
  { texto: '¿Quién escribió "El pendulo de Foucault"?', opciones: ['Italo Calvino', 'Umberto Eco', 'Elsa Morante', 'Natalia Ginzburg'], respuesta: 1 },
  { texto: '¿Quién escribió "Si una noche de invierno un viajero"?', opciones: ['Umberto Eco', 'Italo Calvino', 'Leonardo Sciascia', 'Cesare Pavese'], respuesta: 1 },
  { texto: '¿Quién escribió "Las ciudades invisibles"?', opciones: ['Umberto Eco', 'Italo Calvino', 'Primo Levi', 'Alberto Moravia'], respuesta: 1 },
  { texto: '¿Quién escribió "Si esto es un hombre"?', opciones: ['Alberto Moravia', 'Cesare Pavese', 'Primo Levi', 'Italo Svevo'], respuesta: 2 },
  { texto: '¿Quién escribió "La conciencia de Zeno"?', opciones: ['Luigi Pirandello', 'Italo Svevo', 'Giovanni Verga', 'Carlo Levi'], respuesta: 1 },
  { texto: '¿Quién escribió "El proceso" de Kafka?', opciones: ['Stefan Zweig', 'Franz Kafka', 'Robert Musil', 'Hermann Broch'], respuesta: 1 },
  { texto: '¿Quién escribió "El hombre sin atributos"?', opciones: ['Franz Kafka', 'Robert Musil', 'Hermann Broch', 'Stefan Zweig'], respuesta: 1 },
  { texto: '¿Quién escribió "El mundo de ayer"?', opciones: ['Robert Musil', 'Stefan Zweig', 'Hermann Broch', 'Joseph Roth'], respuesta: 1 },
  { texto: '¿Quién escribió "La marcha Radetzky"?', opciones: ['Stefan Zweig', 'Hermann Broch', 'Joseph Roth', 'Arthur Schnitzler'], respuesta: 2 },
  { texto: '¿Quién escribió "Buddenbrooks"?', opciones: ['Hermann Hesse', 'Thomas Mann', 'Günter Grass', 'Heinrich Böll'], respuesta: 1 },
  { texto: '¿Quién escribió "La montaña mágica"?', opciones: ['Hermann Hesse', 'Thomas Mann', 'Stefan Zweig', 'Rainer Maria Rilke'], respuesta: 1 },
  { texto: '¿Quién escribió "El tambor de hojalata"?', opciones: ['Heinrich Böll', 'Günter Grass', 'Peter Handke', 'Uwe Johnson'], respuesta: 1 },
  { texto: '¿Quién escribió "Steppenwolf" (El lobo estepario)?', opciones: ['Thomas Mann', 'Hermann Hesse', 'Franz Kafka', 'Robert Musil'], respuesta: 1 },
  { texto: '¿Quién escribió "Demian"?', opciones: ['Thomas Mann', 'Stefan Zweig', 'Hermann Hesse', 'Rainer Maria Rilke'], respuesta: 2 },
  { texto: '¿Quién escribió "Las tribulaciones del estudiante Törless"?', opciones: ['Franz Kafka', 'Robert Musil', 'Hermann Hesse', 'Heinrich Mann'], respuesta: 1 },
  { texto: '¿Quién escribió "En busca del tiempo perdido"?', opciones: ['André Gide', 'Marcel Proust', 'Gustave Flaubert', 'Émile Zola'], respuesta: 1 },
  { texto: '¿Quién escribió "Las flores del mal"?', opciones: ['Paul Verlaine', 'Arthur Rimbaud', 'Charles Baudelaire', 'Stéphane Mallarmé'], respuesta: 2 },
  { texto: '¿Quién escribió "El rojo y el negro"?', opciones: ['Honoré de Balzac', 'Gustave Flaubert', 'Stendhal', 'Émile Zola'], respuesta: 2 },
  { texto: '¿Quién escribió "Germinal"?', opciones: ['Victor Hugo', 'Gustave Flaubert', 'Honoré de Balzac', 'Émile Zola'], respuesta: 3 },
  { texto: '¿Quién escribió "Papá Goriot"?', opciones: ['Émile Zola', 'Gustave Flaubert', 'Honoré de Balzac', 'Victor Hugo'], respuesta: 2 },
  { texto: '¿Quién escribió "El proceso" y "El castillo"?', opciones: ['Robert Musil', 'Stefan Zweig', 'Franz Kafka', 'Hermann Hesse'], respuesta: 2 },
  { texto: '¿Quién escribió "Cándido"?', opciones: ['Jean-Jacques Rousseau', 'Voltaire', 'Denis Diderot', 'Montesquieu'], respuesta: 1 },
  { texto: '¿Quién escribió "Robinson Crusoe"?', opciones: ['Jonathan Swift', 'Daniel Defoe', 'Henry Fielding', 'Samuel Richardson'], respuesta: 1 },
  { texto: '¿Quién escribió "Los viajes de Gulliver"?', opciones: ['Daniel Defoe', 'Henry Fielding', 'Jonathan Swift', 'Lawrence Sterne'], respuesta: 2 },
  { texto: '¿Quién escribió "David Copperfield"?', opciones: ['William Thackeray', 'Charles Dickens', 'Thomas Hardy', 'George Eliot'], respuesta: 1 },
  { texto: '¿Quién escribió "Oliver Twist"?', opciones: ['William Thackeray', 'Charles Dickens', 'Anthony Trollope', 'Wilkie Collins'], respuesta: 1 },
  { texto: '¿Quién escribió "Jane Eyre"?', opciones: ['Emily Brontë', 'Anne Brontë', 'Charlotte Brontë', 'George Eliot'], respuesta: 2 },
  { texto: '¿Quién escribió "Tess of the d\'Urbervilles"?', opciones: ['Thomas Hardy', 'George Eliot', 'Anthony Trollope', 'George Gissing'], respuesta: 0 },
  { texto: '¿Quién escribió "Mrs Dalloway"?', opciones: ['Katherine Mansfield', 'Dorothy Richardson', 'Virginia Woolf', 'Rebecca West'], respuesta: 2 },
  { texto: '¿Quién escribió "Al faro"?', opciones: ['Katherine Mansfield', 'Virginia Woolf', 'E.M. Forster', 'D.H. Lawrence'], respuesta: 1 },
  { texto: '¿Quién escribió "Pasaje a la India"?', opciones: ['Joseph Conrad', 'D.H. Lawrence', 'E.M. Forster', 'Rudyard Kipling'], respuesta: 2 },
  { texto: '¿Quién escribió "El corazón de las tinieblas"?', opciones: ['Rudyard Kipling', 'E.M. Forster', 'Joseph Conrad', 'H.G. Wells'], respuesta: 2 },
  { texto: '¿Quién escribió "El amante de Lady Chatterley"?', opciones: ['E.M. Forster', 'Joseph Conrad', 'D.H. Lawrence', 'Aldous Huxley'], respuesta: 2 },
  { texto: '¿Quién escribió "Un mundo feliz"?', opciones: ['George Orwell', 'Aldous Huxley', 'H.G. Wells', 'Arthur C. Clarke'], respuesta: 1 },
  { texto: '¿Quién escribió "La máquina del tiempo"?', opciones: ['Jules Verne', 'H.G. Wells', 'Arthur C. Clarke', 'Isaac Asimov'], respuesta: 1 },
  { texto: '¿Quién escribió "Rebelión en la granja"?', opciones: ['Aldous Huxley', 'H.G. Wells', 'George Orwell', 'Evelyn Waugh'], respuesta: 2 },
  { texto: '¿Quién escribió "El gran Gatsby"?', opciones: ['Ernest Hemingway', 'John Steinbeck', 'F. Scott Fitzgerald', 'William Faulkner'], respuesta: 2 },
  { texto: '¿Quién escribió "Al este del Edén"?', opciones: ['F. Scott Fitzgerald', 'Ernest Hemingway', 'John Steinbeck', 'William Faulkner'], respuesta: 2 },
  { texto: '¿Quién escribió "Las uvas de la ira"?', opciones: ['Ernest Hemingway', 'John Steinbeck', 'William Faulkner', 'Sinclair Lewis'], respuesta: 1 },
  { texto: '¿Quién escribió "El viejo y el mar"?', opciones: ['John Steinbeck', 'William Faulkner', 'Ernest Hemingway', 'F. Scott Fitzgerald'], respuesta: 2 },
  { texto: '¿Quién escribió "El sonido y la furia"?', opciones: ['Ernest Hemingway', 'William Faulkner', 'John Dos Passos', 'Thomas Wolfe'], respuesta: 1 },
  { texto: '¿Quién escribió "En el camino"?', opciones: ['Allen Ginsberg', 'Jack Kerouac', 'William S. Burroughs', 'Lawrence Ferlinghetti'], respuesta: 1 },
  { texto: '¿Quién escribió "Aullido"?', opciones: ['Jack Kerouac', 'Allen Ginsberg', 'Gregory Corso', 'Lawrence Ferlinghetti'], respuesta: 1 },
  { texto: '¿Quién escribió "El festín desnudo"?', opciones: ['Jack Kerouac', 'Allen Ginsberg', 'William S. Burroughs', 'Norman Mailer'], respuesta: 2 },
  { texto: '¿Quién escribió "Beloved"?', opciones: ['Alice Walker', 'Maya Angelou', 'Toni Morrison', 'Zora Neale Hurston'], respuesta: 2 },
  { texto: '¿Quién escribió "El color púrpura"?', opciones: ['Toni Morrison', 'Maya Angelou', 'Alice Walker', 'Zora Neale Hurston'], respuesta: 2 },
  { texto: '¿Quién escribió "Invisible Man"?', opciones: ['Richard Wright', 'James Baldwin', 'Ralph Ellison', 'Langston Hughes'], respuesta: 2 },
  { texto: '¿Quién escribió "Beloved" y ganó el Nobel en 1993?', opciones: ['Alice Walker', 'Maya Angelou', 'Toni Morrison', 'Gloria Naylor'], respuesta: 2 },
  { texto: '¿Quién escribió "Catch-22"?', opciones: ['Kurt Vonnegut', 'Joseph Heller', 'Norman Mailer', 'Philip Roth'], respuesta: 1 },
  { texto: '¿Quién escribió "Matadero cinco"?', opciones: ['Joseph Heller', 'Norman Mailer', 'Kurt Vonnegut', 'John Updike'], respuesta: 2 },
  { texto: '¿Quién escribió "El tambor de hojalata" y ganó el Nobel?', opciones: ['Heinrich Böll', 'Günter Grass', 'Peter Handke', 'Christa Wolf'], respuesta: 1 },
  { texto: '¿Quién escribió "El juego del ángel"?', opciones: ['Arturo Pérez-Reverte', 'Carlos Ruiz Zafón', 'Javier Marías', 'Eduardo Mendoza'], respuesta: 1 },
  { texto: '¿Quién escribió "Cien años de soledad" y cuándo ganó el Nobel?', opciones: ['García Márquez, 1980', 'García Márquez, 1982', 'García Márquez, 1985', 'García Márquez, 1990'], respuesta: 1 },
  { texto: '¿Quién escribió "Fiesta en la madriguera"?', opciones: ['Juan Pablo Villalobos', 'Valeria Luiselli', 'Jorge Volpi', 'Álvaro Enrigue'], respuesta: 0 },
  { texto: '¿Quién escribió "Los emigrantes"?', opciones: ['Peter Handke', 'W.G. Sebald', 'Christa Wolf', 'Elfriede Jelinek'], respuesta: 1 },
  { texto: '¿Quién escribió "Austerlitz"?', opciones: ['Peter Handke', 'Christa Wolf', 'W.G. Sebald', 'Günter Grass'], respuesta: 2 },
  { texto: '¿Quién escribió "La pianista"?', opciones: ['Christa Wolf', 'Elfriede Jelinek', 'Ingeborg Bachmann', 'Ilse Aichinger'], respuesta: 1 },
  { texto: '¿Quién escribió "El maestro y Margarita"?', opciones: ['Mijaíl Bulgakov', 'Ilya Ehrenburg', 'Boris Pasternak', 'Aleksandr Solzhenitsyn'], respuesta: 0 },
  { texto: '¿Quién escribió "Doctor Zhivago"?', opciones: ['Mijaíl Bulgakov', 'Aleksandr Solzhenitsyn', 'Boris Pasternak', 'Mikhail Sholokhov'], respuesta: 2 },
  { texto: '¿Quién escribió "Archipiélago Gulag"?', opciones: ['Boris Pasternak', 'Mijaíl Bulgakov', 'Vasily Grossman', 'Aleksandr Solzhenitsyn'], respuesta: 3 },
  { texto: '¿Quién escribió "Un día en la vida de Iván Denísovich"?', opciones: ['Boris Pasternak', 'Aleksandr Solzhenitsyn', 'Vasily Grossman', 'Andrei Platonov'], respuesta: 1 },
  { texto: '¿Quién escribió "El jugador"?', opciones: ['Iván Turguénev', 'Fiódor Dostoyevski', 'León Tolstói', 'Nikolái Gógol'], respuesta: 1 },
  { texto: '¿Quién escribió "Almas muertas"?', opciones: ['León Tolstói', 'Fiódor Dostoyevski', 'Nikolái Gógol', 'Iván Turguénev'], respuesta: 2 },
  { texto: '¿Quién escribió "Padres e hijos"?', opciones: ['Nikolái Gógol', 'León Tolstói', 'Fiódor Dostoyevski', 'Iván Turguénev'], respuesta: 3 },
  { texto: '¿Quién escribió "El jardín de los cerezos"?', opciones: ['Iván Turguénev', 'Máximo Gorki', 'Antón Chéjov', 'Aleksandr Ostrovsky'], respuesta: 2 },
  { texto: '¿Quién escribió "La gaviota"?', opciones: ['Máximo Gorki', 'Antón Chéjov', 'León Tolstói', 'Iván Turguénev'], respuesta: 1 },
  { texto: '¿Quién escribió "Hamlet" y en qué año aproximado?', opciones: ['Shakespeare, 1590', 'Shakespeare, 1600', 'Shakespeare, 1610', 'Shakespeare, 1620'], respuesta: 1 },
  { texto: '¿Cuál es la obra de teatro más famosa de Molière?', opciones: ['El avaro', 'El misántropo', 'El burgués gentilhombre', 'Tartufo'], respuesta: 3 },
  { texto: '¿Quién escribió "Esperando a Godot"?', opciones: ['Harold Pinter', 'Samuel Beckett', 'Eugène Ionesco', 'Jean Genet'], respuesta: 1 },
  { texto: '¿Quién escribió "La cantante calva"?', opciones: ['Samuel Beckett', 'Jean Genet', 'Eugène Ionesco', 'Harold Pinter'], respuesta: 2 },
  { texto: '¿Quién escribió "Las criadas"?', opciones: ['Eugène Ionesco', 'Samuel Beckett', 'Jean Genet', 'Harold Pinter'], respuesta: 2 },
  { texto: '¿Quién escribió "El cartero siempre llama dos veces"?', opciones: ['Raymond Chandler', 'Dashiell Hammett', 'James M. Cain', 'Mickey Spillane'], respuesta: 2 },
  { texto: '¿Quién escribió "El largo adiós"?', opciones: ['Dashiell Hammett', 'Raymond Chandler', 'James M. Cain', 'Ross Macdonald'], respuesta: 1 },
  { texto: '¿Quién es el protagonista de las novelas de Raymond Chandler?', opciones: ['Sam Spade', 'Mike Hammer', 'Philip Marlowe', 'Lew Archer'], respuesta: 2 },
  { texto: '¿Quién escribió "El padrino"?', opciones: ['Mario Puzo', 'Don DeLillo', 'Elmore Leonard', 'James Ellroy'], respuesta: 0 },
  { texto: '¿Quién escribió "Ruido de fondo" (White Noise)?', opciones: ['Philip Roth', 'John Updike', 'Don DeLillo', 'Thomas Pynchon'], respuesta: 2 },
  { texto: '¿Quién escribió "El arco iris de gravedad"?', opciones: ['Don DeLillo', 'Thomas Pynchon', 'John Barth', 'William Gaddis'], respuesta: 1 },
  { texto: '¿Quién escribió "Beloved" y en qué año ganó el Nobel?', opciones: ['Toni Morrison, 1991', 'Toni Morrison, 1993', 'Toni Morrison, 1995', 'Toni Morrison, 1998'], respuesta: 1 },
  { texto: '¿Quién escribió "El cuento de la criada"?', opciones: ['Joyce Carol Oates', 'Margaret Atwood', 'Doris Lessing', 'Ursula K. Le Guin'], respuesta: 1 },
  { texto: '¿Quién escribió "Alias Grace"?', opciones: ['Carol Shields', 'Margaret Atwood', 'Alice Munro', 'Anne Michaels'], respuesta: 1 },
  { texto: '¿Quién escribió "Las correcciones"?', opciones: ['David Foster Wallace', 'Jonathan Franzen', 'Jeffrey Eugenides', 'Rick Moody'], respuesta: 1 },
  { texto: '¿Quién escribió "La broma infinita"?', opciones: ['Jonathan Franzen', 'Jeffrey Eugenides', 'David Foster Wallace', 'Don DeLillo'], respuesta: 2 },
  { texto: '¿Quién escribió "Las vírgenes suicidas"?', opciones: ['Jonathan Franzen', 'Jeffrey Eugenides', 'Rick Moody', 'A.M. Homes'], respuesta: 1 },
  { texto: '¿Quién escribió "Middlesex"?', opciones: ['Jonathan Franzen', 'Jeffrey Eugenides', 'Philip Roth', 'John Irving'], respuesta: 1 },
  { texto: '¿Quién escribió "El mundo según Garp"?', opciones: ['Philip Roth', 'John Updike', 'John Irving', 'Saul Bellow'], respuesta: 2 },
  { texto: '¿Quién escribió "Herzog"?', opciones: ['John Updike', 'Philip Roth', 'Saul Bellow', 'Norman Mailer'], respuesta: 2 },
  { texto: '¿Quién escribió "La conjura de los necios"?', opciones: ['Walker Percy', 'John Kennedy Toole', 'Barry Hannah', 'Larry Brown'], respuesta: 1 },
  { texto: '¿Quién escribió "Beloved" (Toni Morrison) y de qué país es?', opciones: ['Canadá', 'Estados Unidos', 'Jamaica', 'Reino Unido'], respuesta: 1 },
  { texto: '¿Quién escribió "El perseguidor"?', opciones: ['Jorge Luis Borges', 'Julio Cortázar', 'Mario Vargas Llosa', 'Gabriel García Márquez'], respuesta: 1 },
  { texto: '¿En qué año se publicó "Rayuela" de Cortázar?', opciones: ['1960', '1963', '1967', '1970'], respuesta: 1 },
  { texto: '¿Quién escribió "El juguete rabioso"?', opciones: ['Manuel Puig', 'Roberto Arlt', 'Ernesto Sábato', 'Leopoldo Marechal'], respuesta: 1 },
  { texto: '¿Quién escribió "Historia universal de la infamia"?', opciones: ['Julio Cortázar', 'Jorge Luis Borges', 'Adolfo Bioy Casares', 'Silvina Ocampo'], respuesta: 1 },
  { texto: '¿Quién escribió "Los cachorros"?', opciones: ['Gabriel García Márquez', 'Julio Cortázar', 'Mario Vargas Llosa', 'Jorge Amado'], respuesta: 2 },
  { texto: '¿Quién escribió "El corazón es un cazador solitario"?', opciones: ['Carson McCullers', 'Flannery O\'Connor', 'Katherine Anne Porter', 'Eudora Welty'], respuesta: 0 },
  { texto: '¿Quién escribió "A sangre fría"?', opciones: ['Norman Mailer', 'Gore Vidal', 'Truman Capote', 'Tom Wolfe'], respuesta: 2 },
  { texto: '¿Quién escribió "Desayuno en Tiffany\'s"?', opciones: ['Gore Vidal', 'Truman Capote', 'Norman Mailer', 'James Baldwin'], respuesta: 1 },
  { texto: '¿Quién escribió "Giovanni\'s Room"?', opciones: ['Truman Capote', 'Gore Vidal', 'James Baldwin', 'John Rechy'], respuesta: 2 },
  { texto: '¿Quién escribió "El libro del desasosiego"?', opciones: ['José Saramago', 'Fernando Pessoa', 'Eça de Queirós', 'Miguel Torga'], respuesta: 1 },
  { texto: '¿Quién escribió "El ensayo sobre la ceguera"?', opciones: ['Fernando Pessoa', 'José Saramago', 'Lídia Jorge', 'António Lobo Antunes'], respuesta: 1 },
  { texto: '¿Quién escribió "Memorial del convento"?', opciones: ['António Lobo Antunes', 'Lídia Jorge', 'José Saramago', 'Fernando Pessoa'], respuesta: 2 },
  { texto: '¿Quién escribió "Don Casmurro"?', opciones: ['Jorge Amado', 'Clarice Lispector', 'Machado de Assis', 'Guimarães Rosa'], respuesta: 2 },
  { texto: '¿Quién escribió "Grande Sertão: Veredas"?', opciones: ['Machado de Assis', 'Jorge Amado', 'Clarice Lispector', 'João Guimarães Rosa'], respuesta: 3 },
  { texto: '¿Quién escribió "La pasión según G.H."?', opciones: ['Jorge Amado', 'Machado de Assis', 'Clarice Lispector', 'Graciliano Ramos'], respuesta: 2 },
  { texto: '¿Quién escribió "Gabriela, clavo y canela"?', opciones: ['Machado de Assis', 'Jorge Amado', 'Clarice Lispector', 'Guimarães Rosa'], respuesta: 1 },
  { texto: '¿Quién escribió "Vidas secas"?', opciones: ['Jorge Amado', 'Graciliano Ramos', 'José Lins do Rego', 'Érico Veríssimo'], respuesta: 1 },
  { texto: '¿Qué Premio Nobel obtuvo Gabriela Mistral?', opciones: ['Nobel de Paz', 'Nobel de Literatura', 'Nobel de la Paz', 'No ganó el Nobel'], respuesta: 1 },
  { texto: '¿Quién escribió "El túnel del tiempo"?', opciones: ['Julio Cortázar', 'Jorge Luis Borges', 'Ernesto Sábato', 'Adolfo Bioy Casares'], respuesta: 2 },
  { texto: '¿Quién escribió "Poeta en Nueva York"?', opciones: ['Juan Ramón Jiménez', 'Antonio Machado', 'Federico García Lorca', 'Rafael Alberti'], respuesta: 2 },
  { texto: '¿Quién escribió "Campos de Castilla"?', opciones: ['Juan Ramón Jiménez', 'Antonio Machado', 'Federico García Lorca', 'Miguel de Unamuno'], respuesta: 1 },
  { texto: '¿Quién escribió "Platero y yo"?', opciones: ['Antonio Machado', 'Federico García Lorca', 'Juan Ramón Jiménez', 'Miguel de Unamuno'], respuesta: 2 },
  { texto: '¿Quién escribió "Niebla"?', opciones: ['Pío Baroja', 'José Ortega y Gasset', 'Miguel de Unamuno', 'Azorín'], respuesta: 2 },
  { texto: '¿Quién escribió "La casa de Bernarda Alba"?', opciones: ['Antonio Machado', 'Juan Ramón Jiménez', 'Federico García Lorca', 'Rafael Alberti'], respuesta: 2 },
  { texto: '¿Quién escribió "Romancero gitano"?', opciones: ['Antonio Machado', 'Rafael Alberti', 'Federico García Lorca', 'León Felipe'], respuesta: 2 },
]

export function getPreguntaDelDia(): Pregunta & { indice: number } {
  const dayIndex = Math.floor(Date.now() / (24 * 60 * 60 * 1000))
  const indice = dayIndex % PREGUNTAS.length
  return { ...PREGUNTAS[indice], indice }
}
