export interface Pregunta {
  texto: string
  opciones: string[]
  respuesta: number // índice 0-based de la opción correcta
}

export const PREGUNTAS: Pregunta[] = [
  { texto: '¿Quién escribió "Cien años de soledad"?', opciones: ['Pablo Neruda', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Julio Cortázar'], respuesta: 1 },
  { texto: '¿En qué país transcurre "Don Quijote de la Mancha"?', opciones: ['Portugal', 'Italia', 'España', 'Francia'], respuesta: 2 },
  { texto: '¿Quién escribió "Hamlet"?', opciones: ['Charles Dickens', 'William Shakespeare', 'Oscar Wilde', 'John Milton'], respuesta: 1 },
  { texto: '¿Cómo se llama el protagonista de "El Aleph"?', opciones: ['Borges', 'Fierro', 'Aureliano', 'Raskolnikov'], respuesta: 0 },
  { texto: '¿Quién escribió "La casa de los espíritus"?', opciones: ['Isabel Allende', 'Laura Esquivel', 'Elena Poniatowska', 'Rosario Castellanos'], respuesta: 0 },
  { texto: '¿En qué novela aparece el personaje Atticus Finch?', opciones: ['El gran Gatsby', 'Matar a un ruiseñor', 'Mientras agonizo', 'El sonido y la furia'], respuesta: 1 },
  { texto: '¿Quién escribió "Rayuela"?', opciones: ['Ernesto Sábato', 'Julio Cortázar', 'Jorge Luis Borges', 'Adolfo Bioy Casares'], respuesta: 1 },
  { texto: '¿Cuál es el apellido del protagonista de "Crimen y castigo"?', opciones: ['Karenin', 'Karamazov', 'Raskolnikov', 'Oblomov'], respuesta: 2 },
  { texto: '¿Quién escribió "Orgullo y prejuicio"?', opciones: ['Charlotte Brontë', 'Mary Shelley', 'George Eliot', 'Jane Austen'], respuesta: 3 },
  { texto: '¿En qué siglo vivió Miguel de Cervantes?', opciones: ['XIV', 'XV', 'XVI-XVII', 'XVIII'], respuesta: 2 },
  { texto: '¿Quién es el autor de "El extranjero"?', opciones: ['Jean-Paul Sartre', 'Albert Camus', 'Simone de Beauvoir', 'André Gide'], respuesta: 1 },
  { texto: '¿Cómo se llama la ballena blanca en "Moby Dick"?', opciones: ['Moby', 'Leviatán', 'No tiene nombre propio', 'Moby Dick'], respuesta: 3 },
  { texto: '¿Quién escribió "1984"?', opciones: ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H.G. Wells'], respuesta: 2 },
  { texto: '¿Qué narrador usa "El gran Gatsby"?', opciones: ['Jay Gatsby', 'Daisy Buchanan', 'Nick Carraway', 'Tom Buchanan'], respuesta: 2 },
  { texto: '¿Quién escribió "Ficciones"?', opciones: ['Julio Cortázar', 'Jorge Luis Borges', 'Bioy Casares', 'Roberto Arlt'], respuesta: 1 },
  { texto: '¿En qué obra de Shakespeare aparece Ofelia?', opciones: ['Macbeth', 'Otelo', 'El rey Lear', 'Hamlet'], respuesta: 3 },
  { texto: '¿Quién escribió "Pedro Páramo"?', opciones: ['Carlos Fuentes', 'Juan Rulfo', 'Augusto Monterroso', 'José Emilio Pacheco'], respuesta: 1 },
  { texto: '¿Cuál es la primera línea de "Anna Karénina"?', opciones: ['Todo era oscuridad y silencio', 'Todas las familias felices se parecen', 'Llámame Ismael', 'Era el mejor de los tiempos'], respuesta: 1 },
  { texto: '¿Quién escribió "El señor de los anillos"?', opciones: ['C.S. Lewis', 'J.R.R. Tolkien', 'Terry Pratchett', 'George R.R. Martin'], respuesta: 1 },
  { texto: '¿Qué personaje vive en Baker Street 221B?', opciones: ['Hercule Poirot', 'Philip Marlowe', 'Sherlock Holmes', 'Auguste Dupin'], respuesta: 2 },
  { texto: '¿Quién escribió "La metamorfosis"?', opciones: ['Stefan Zweig', 'Thomas Mann', 'Hermann Hesse', 'Franz Kafka'], respuesta: 3 },
  { texto: '¿En qué ciudad transcurre "Ulises" de James Joyce?', opciones: ['Londres', 'Dublín', 'Edimburgo', 'Belfast'], respuesta: 1 },
  { texto: '¿Quién escribió "Los miserables"?', opciones: ['Gustave Flaubert', 'Honoré de Balzac', 'Émile Zola', 'Victor Hugo'], respuesta: 3 },
  { texto: '¿Cómo se llama el protagonista de "El proceso" de Kafka?', opciones: ['Gregor Samsa', 'Josef K.', 'Karl Rossmann', 'Georg Bendemann'], respuesta: 1 },
  { texto: '¿Qué autor ganó el Nobel con "Beloved"?', opciones: ['Maya Angelou', 'Alice Walker', 'Toni Morrison', 'Zora Neale Hurston'], respuesta: 2 },
  { texto: '¿Quién escribió "Don Segundo Sombra"?', opciones: ['José Hernández', 'Ricardo Güiraldes', 'Leopoldo Lugones', 'Horacio Quiroga'], respuesta: 1 },
  { texto: '¿En qué obra aparece el personaje Huckleberry Finn?', opciones: ['Tom Sawyer', 'Las aventuras de Huck Finn', 'Ambos', 'Ninguno'], respuesta: 2 },
  { texto: '¿Quién escribió "Frankenstein"?', opciones: ['Bram Stoker', 'Ann Radcliffe', 'Mary Shelley', 'Edgar Allan Poe'], respuesta: 2 },
  { texto: '¿De qué país era el autor de "El túnel"?', opciones: ['Chile', 'Uruguay', 'Argentina', 'México'], respuesta: 2 },
  { texto: '¿Quién escribió "Middlemarch"?', opciones: ['Jane Austen', 'George Eliot', 'Elizabeth Gaskell', 'Thomas Hardy'], respuesta: 1 },
  { texto: '¿En qué década se publicó "Cien años de soledad"?', opciones: ['1950', '1960', '1970', '1980'], respuesta: 1 },
  { texto: '¿Qué movimiento literario lideró García Márquez junto a otros autores latinoamericanos?', opciones: ['Romanticismo', 'Modernismo', 'Realismo mágico', 'Surrealismo'], respuesta: 2 },
  { texto: '¿Quién escribió "El amor en los tiempos del cólera"?', opciones: ['Mario Vargas Llosa', 'Gabriel García Márquez', 'Jorge Amado', 'Isabel Allende'], respuesta: 1 },
  { texto: '¿Cuál es el nombre del protagonista de "El principito"?', opciones: ['El Principito', 'Petit', 'No tiene nombre', 'Pepito'], respuesta: 0 },
  { texto: '¿Quién escribió "El principito"?', opciones: ['Jules Verne', 'Antoine de Saint-Exupéry', 'Albert Camus', 'Jean Cocteau'], respuesta: 1 },
  { texto: '¿En qué obra aparece el personaje Jean Valjean?', opciones: ['El conde de Montecristo', 'Los miserables', 'Germinal', 'Nana'], respuesta: 1 },
  { texto: '¿Quién escribió "Los detectives salvajes"?', opciones: ['Roberto Bolaño', 'César Aira', 'Ricardo Piglia', 'Juan Villoro'], respuesta: 0 },
  { texto: '¿Qué novela comienza con "Llámame Ismael"?', opciones: ['Billy Budd', 'Lord Jim', 'Moby Dick', 'Nostromo'], respuesta: 2 },
  { texto: '¿Quién escribió "Madame Bovary"?', opciones: ['Victor Hugo', 'Honoré de Balzac', 'Gustave Flaubert', 'Stendhal'], respuesta: 2 },
  { texto: '¿Quién escribió "Crimen y castigo"?', opciones: ['León Tolstói', 'Fiódor Dostoyevski', 'Iván Turguénev', 'Nikolái Gógol'], respuesta: 1 },
  { texto: '¿Qué novela de Kafka termina sin final explícito porque murió antes de terminarla?', opciones: ['La metamorfosis', 'El proceso', 'El castillo', 'América'], respuesta: 2 },
  { texto: '¿Quién escribió "Cumbres borrascosas"?', opciones: ['Jane Austen', 'Charlotte Brontë', 'Emily Brontë', 'Anne Brontë'], respuesta: 2 },
  { texto: '¿Qué autor argentino escribió "Sobre héroes y tumbas"?', opciones: ['Jorge Luis Borges', 'Ernesto Sábato', 'Julio Cortázar', 'Manuel Puig'], respuesta: 1 },
  { texto: '¿Quién escribió "El nombre de la rosa"?', opciones: ['Umberto Eco', 'Italo Calvino', 'Leonardo Sciascia', 'Luigi Pirandello'], respuesta: 0 },
  { texto: '¿En qué idioma escribió originalmente "La divina comedia"?', opciones: ['Latín', 'Italiano antiguo (toscano)', 'Francés', 'Provenzal'], respuesta: 1 },
  { texto: '¿Quién escribió "La divina comedia"?', opciones: ['Petrarca', 'Boccaccio', 'Dante Alighieri', 'Ariosto'], respuesta: 2 },
  { texto: '¿Cuál es el apellido de los protagonistas de "Orgullo y prejuicio"?', opciones: ['Bennet', 'Darcy', 'Woodhouse', 'Dashwood'], respuesta: 0 },
  { texto: '¿Quién escribió "El retrato de Dorian Gray"?', opciones: ['Arthur Conan Doyle', 'Oscar Wilde', 'Robert Louis Stevenson', 'Bram Stoker'], respuesta: 1 },
  { texto: '¿Cuántos libros tiene la saga "Harry Potter"?', opciones: ['5', '6', '7', '8'], respuesta: 2 },
  { texto: '¿Quién es el autor de "El hobbit"?', opciones: ['C.S. Lewis', 'J.R.R. Tolkien', 'Philip Pullman', 'Ursula K. Le Guin'], respuesta: 1 },
  { texto: '¿Qué Premio Nobel de Literatura ganó Pablo Neruda?', opciones: ['1961', '1967', '1971', '1975'], respuesta: 2 },
  { texto: '¿Quién escribió "Bodas de sangre"?', opciones: ['Antonio Machado', 'Federico García Lorca', 'Rafael Alberti', 'Miguel Hernández'], respuesta: 1 },
  { texto: '¿En qué siglo vivió William Shakespeare?', opciones: ['XIV-XV', 'XV-XVI', 'XVI-XVII', 'XVII-XVIII'], respuesta: 2 },
  { texto: '¿Quién escribió "La náusea"?', opciones: ['Albert Camus', 'Jean-Paul Sartre', 'Simone de Beauvoir', 'Maurice Merleau-Ponty'], respuesta: 1 },
  { texto: '¿Cómo se llama el mayordomo de "El gran Gatsby"?', opciones: ['No tiene', 'James', 'Thomas', 'Wilson'], respuesta: 0 },
  { texto: '¿Quién escribió "El jugador" y "Los hermanos Karamázov"?', opciones: ['León Tolstói', 'Iván Turguénev', 'Fiódor Dostoyevski', 'Antón Chéjov'], respuesta: 2 },
  { texto: '¿Qué autor colombiano ganó el Nobel de Literatura en 1982?', opciones: ['Jorge Isaacs', 'Rafael Pombo', 'Gabriel García Márquez', 'Tomás González'], respuesta: 2 },
  { texto: '¿Quién escribió "2001: Odisea del espacio"?', opciones: ['Isaac Asimov', 'Arthur C. Clarke', 'Ray Bradbury', 'Philip K. Dick'], respuesta: 1 },
  { texto: '¿En qué país nació Gabriel García Márquez?', opciones: ['Venezuela', 'Colombia', 'México', 'Perú'], respuesta: 1 },
  { texto: '¿Qué movimiento literario representa Edgar Allan Poe?', opciones: ['Romanticismo oscuro / gótico', 'Realismo', 'Naturalismo', 'Modernismo'], respuesta: 0 },
  { texto: '¿Quién escribió "La guerra y la paz"?', opciones: ['Fiódor Dostoyevski', 'Antón Chéjov', 'León Tolstói', 'Iván Turguénev'], respuesta: 2 },
  { texto: '¿Cuántos años tiene el protagonista al inicio de "El guardián entre el centeno"?', opciones: ['14', '15', '16', '17'], respuesta: 2 },
  { texto: '¿Quién escribió "El guardián entre el centeno"?', opciones: ['J.D. Salinger', 'Jack Kerouac', 'F. Scott Fitzgerald', 'Ernest Hemingway'], respuesta: 0 },
  { texto: '¿Cuál es el subtítulo de "Frankenstein"?', opciones: ['El monstruo moderno', 'El Prometeo moderno', 'El experimento', 'El creador'], respuesta: 1 },
  { texto: '¿Quién escribió "Crónica de una muerte anunciada"?', opciones: ['Isabel Allende', 'Mario Vargas Llosa', 'Gabriel García Márquez', 'Carlos Fuentes'], respuesta: 2 },
  { texto: '¿En qué país transcurre "Doña Bárbara" de Rómulo Gallegos?', opciones: ['Colombia', 'Ecuador', 'Venezuela', 'Bolivia'], respuesta: 2 },
  { texto: '¿Quién escribió "El Martín Fierro"?', opciones: ['Ricardo Güiraldes', 'Esteban Echeverría', 'José Hernández', 'Domingo Sarmiento'], respuesta: 2 },
  { texto: '¿Qué forma poética usa "El Martín Fierro"?', opciones: ['Soneto', 'Haiku', 'Décimas (sextinas gauchescas)', 'Verso libre'], respuesta: 2 },
  { texto: '¿Quién escribió "Fahrenheit 451"?', opciones: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'Philip K. Dick'], respuesta: 2 },
  { texto: '¿Qué significa el número 451 en "Fahrenheit 451"?', opciones: ['El año en que ocurre', 'La temperatura a la que arde el papel', 'El número de página clave', 'El código secreto de los rebeldes'], respuesta: 1 },
  { texto: '¿Quién escribió "Lolita"?', opciones: ['Philip Roth', 'John Updike', 'Vladimir Nabokov', 'Saul Bellow'], respuesta: 2 },
  { texto: '¿En qué idioma escribió originalmente Nabokov "Lolita"?', opciones: ['Ruso', 'Francés', 'Inglés', 'Alemán'], respuesta: 2 },
  { texto: '¿Quién escribió "El alquimista"?', opciones: ['Jorge Amado', 'Paulo Coelho', 'Clarice Lispector', 'Machado de Assis'], respuesta: 1 },
  { texto: '¿Quién escribió "Fiesta" (The Sun Also Rises)?', opciones: ['F. Scott Fitzgerald', 'Ernest Hemingway', 'John Steinbeck', 'William Faulkner'], respuesta: 1 },
  { texto: '¿Cómo se llama el robot que aparece en "Yo, Robot" de Asimov?', opciones: ['Hal 9000', 'R2D2', 'Robbie', 'Data'], respuesta: 2 },
  { texto: '¿Quién escribió "La insoportable levedad del ser"?', opciones: ['Milan Kundera', 'Bohumil Hrabal', 'Václav Havel', 'Josef Škvorecký'], respuesta: 0 },
  { texto: '¿En qué ciudad transcurre "El perfume" de Patrick Süskind?', opciones: ['Berlín', 'Viena', 'París', 'Londres'], respuesta: 2 },
  { texto: '¿Quién escribió "Como agua para chocolate"?', opciones: ['Ángeles Mastretta', 'Laura Esquivel', 'Elena Poniatowska', 'Rosario Castellanos'], respuesta: 1 },
  { texto: '¿Qué país de origen tiene el autor de "El otoño del patriarca"?', opciones: ['Venezuela', 'Colombia', 'Cuba', 'México'], respuesta: 1 },
  { texto: '¿Quién escribió "Los pasos perdidos"?', opciones: ['Jorge Amado', 'Alejo Carpentier', 'Guillermo Cabrera Infante', 'José Lezama Lima'], respuesta: 1 },
  { texto: '¿Quién escribió "Ficciones"?', opciones: ['Julio Cortázar', 'Jorge Luis Borges', 'Macedonio Fernández', 'Silvina Ocampo'], respuesta: 1 },
  { texto: '¿Qué significa "haiku"?', opciones: ['Poema de veinte sílabas', 'Poema corto japonés de tres versos', 'Canción popular china', 'Relato breve coreano'], respuesta: 1 },
  { texto: '¿Quién escribió los poemas de "Residencia en la tierra"?', opciones: ['César Vallejo', 'Pablo Neruda', 'Octavio Paz', 'Vicente Huidobro'], respuesta: 1 },
  { texto: '¿En qué ciudad nació Pablo Neruda?', opciones: ['Santiago', 'Parral', 'Valparaíso', 'Temuco'], respuesta: 1 },
  { texto: '¿Qué escritor inventó al detective Auguste Dupin?', opciones: ['Arthur Conan Doyle', 'Agatha Christie', 'Edgar Allan Poe', 'Wilkie Collins'], respuesta: 2 },
  { texto: '¿Quién escribió "La condición humana"?', opciones: ['André Malraux', 'Albert Camus', 'Jean-Paul Sartre', 'André Gide'], respuesta: 0 },
  { texto: '¿En qué obra de García Márquez salen los Buendía?', opciones: ['El otoño del patriarca', 'El amor en los tiempos del cólera', 'Cien años de soledad', 'La hojarasca'], respuesta: 2 },
  { texto: '¿Cuántas obras de teatro escribió Shakespeare aproximadamente?', opciones: ['20', '27', '37', '45'], respuesta: 2 },
  { texto: '¿Quién escribió "Las flores del mal"?', opciones: ['Paul Verlaine', 'Arthur Rimbaud', 'Stéphane Mallarmé', 'Charles Baudelaire'], respuesta: 3 },
  { texto: '¿Quién escribió "El túnel"?', opciones: ['Jorge Luis Borges', 'Julio Cortázar', 'Ernesto Sábato', 'Adolfo Bioy Casares'], respuesta: 2 },
  { texto: '¿Quién escribió "Pantaleón y las visitadoras"?', opciones: ['Jorge Luis Borges', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Julio Cortázar'], respuesta: 2 },
  { texto: '¿Quién es el autor de "Rayuela"?', opciones: ['Ernesto Sábato', 'Julio Cortázar', 'Manuel Puig', 'Roberto Arlt'], respuesta: 1 },
  { texto: '¿En qué ciudad vive el detective Hercule Poirot de Agatha Christie?', opciones: ['París', 'Bruselas', 'Londres', 'Ginebra'], respuesta: 2 },
  { texto: '¿Quién escribió "El conde de Montecristo"?', opciones: ['Victor Hugo', 'Alexandre Dumas', 'Émile Zola', 'Stendhal'], respuesta: 1 },
  { texto: '¿Cuál es el nombre real de Mark Twain?', opciones: ['Thomas Clemens', 'Samuel Clemens', 'James Twain', 'Michael Twain'], respuesta: 1 },
  { texto: '¿Quién escribió "La vorágine"?', opciones: ['Rómulo Gallegos', 'José Eustasio Rivera', 'Jorge Isaacs', 'Eduardo Caballero Calderón'], respuesta: 1 },
  { texto: '¿Qué escritor chileno ganó el Nobel de Literatura en 1945?', opciones: ['Pablo Neruda', 'Vicente Huidobro', 'Gabriela Mistral', 'Nicanor Parra'], respuesta: 2 },
  { texto: '¿Quién escribió "Conversación en la catedral"?', opciones: ['Julio Cortázar', 'Gabriel García Márquez', 'Mario Vargas Llosa', 'Carlos Fuentes'], respuesta: 2 },
  { texto: '¿En qué formato está escrita "Rayuela" de Cortázar?', opciones: ['Novela lineal', 'Novela que puede leerse en múltiples órdenes', 'Cuentos intercalados', 'Diario íntimo'], respuesta: 1 },
  { texto: '¿Quién escribió "Veinte poemas de amor y una canción desesperada"?', opciones: ['César Vallejo', 'García Lorca', 'Pablo Neruda', 'Rubén Darío'], respuesta: 2 },
  { texto: '¿Quién escribió "Los olvidados" (libro, no película)?', opciones: ['Juan Rulfo', 'No existe como libro', 'Carlos Monsiváis', 'José Revueltas'], respuesta: 1 },
  { texto: '¿Quién escribió "El jugador" de Dostoyevski?', opciones: ['Fiódor Dostoyevski', 'León Tolstói', 'Antón Chéjov', 'Aleksandr Pushkin'], respuesta: 0 },
  { texto: '¿Cuántos libros componen "El señor de los anillos" como novela?', opciones: ['1', '2', '3', '6'], respuesta: 0 },
  { texto: '¿Quién escribió "La muerte de Artemio Cruz"?', opciones: ['Juan Rulfo', 'Carlos Fuentes', 'Octavio Paz', 'Agustín Yáñez'], respuesta: 1 },
]

export function getPreguntaDelDia(): Pregunta & { indice: number } {
  const dayIndex = Math.floor(Date.now() / (24 * 60 * 60 * 1000))
  const indice = dayIndex % PREGUNTAS.length
  return { ...PREGUNTAS[indice], indice }
}
